// Regenerates src/templates/fonts.data.ts — DejaVu Sans (full Latin-2) embedded
// as base64 data URIs so templates render Slovak/Czech/Polish diacritics with no
// runtime font fetch (the react-pdf font loader decodes data: URIs via atob, so
// this works on the Cloudflare Workers runtime). Run: bun run generate-fonts

const BASE = "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf"

const b64 = async (file: string): Promise<string> => {
    const res = await fetch(`${BASE}/${file}`)
    if (!res.ok) throw new Error(`fetch ${file}: ${res.status}`)
    return Buffer.from(await res.arrayBuffer()).toString("base64")
}

const [reg, bold] = await Promise.all([b64("DejaVuSans.ttf"), b64("DejaVuSans-Bold.ttf")])

const out =
    `// AUTO-GENERATED by 'bun run generate-fonts'. Do not edit by hand.\n` +
    `// DejaVu Sans (Bitstream Vera / public-domain license), embedded as data URIs.\n` +
    `export const DEJAVU_SANS = "data:font/ttf;base64,${reg}"\n` +
    `export const DEJAVU_SANS_BOLD = "data:font/ttf;base64,${bold}"\n`

await Bun.write("src/templates/fonts.data.ts", out)
console.log(`Wrote src/templates/fonts.data.ts (${(out.length / 1024 / 1024).toFixed(2)}MB)`)
