import { Schema } from "effect"
import {
  UUID,
  CountryCode,
  CurrencyCode,
  TaxIdType,
  Email,
  PositiveInt,
} from "./common.ts"

export class Organization extends Schema.Class<Organization>("Organization")({
  id: UUID,
  name: Schema.String,
  legalName: Schema.String,
  addressLine1: Schema.NullOr(Schema.String),
  addressLine2: Schema.NullOr(Schema.String),
  city: Schema.NullOr(Schema.String),
  state: Schema.NullOr(Schema.String),
  postalCode: Schema.NullOr(Schema.String),
  countryCode: CountryCode,
  taxId: Schema.NullOr(Schema.String),
  taxIdType: Schema.NullOr(TaxIdType),
  email: Schema.NullOr(Email),
  phone: Schema.NullOr(Schema.String),
  website: Schema.NullOr(Schema.String),
  bankName: Schema.NullOr(Schema.String),
  bankIban: Schema.NullOr(Schema.String),
  bankSwift: Schema.NullOr(Schema.String),
  bankAccountNumber: Schema.NullOr(Schema.String),
  logoUrl: Schema.NullOr(Schema.String),
  defaultCurrency: CurrencyCode,
  defaultPaymentTermsDays: PositiveInt,
  invoicePrefix: Schema.String,
  nextInvoiceNumber: PositiveInt,
  createdAt: Schema.DateFromString,
  updatedAt: Schema.DateFromString,
}) {}

export class CreateOrganization extends Schema.Class<CreateOrganization>("CreateOrganization")({
  name: Schema.String.pipe(Schema.minLength(1)),
  legalName: Schema.String.pipe(Schema.minLength(1)),
  addressLine1: Schema.optional(Schema.String),
  addressLine2: Schema.optional(Schema.String),
  city: Schema.optional(Schema.String),
  state: Schema.optional(Schema.String),
  postalCode: Schema.optional(Schema.String),
  countryCode: CountryCode,
  taxId: Schema.optional(Schema.String),
  taxIdType: Schema.optional(TaxIdType),
  email: Schema.optional(Email),
  phone: Schema.optional(Schema.String),
  website: Schema.optional(Schema.String),
  bankName: Schema.optional(Schema.String),
  bankIban: Schema.optional(Schema.String),
  bankSwift: Schema.optional(Schema.String),
  bankAccountNumber: Schema.optional(Schema.String),
  logoUrl: Schema.optional(Schema.String),
  defaultCurrency: Schema.optionalWith(CurrencyCode, { default: () => "EUR" as CurrencyCode }),
  defaultPaymentTermsDays: Schema.optionalWith(PositiveInt, { default: () => 30 as PositiveInt }),
  invoicePrefix: Schema.optionalWith(Schema.String, { default: () => "INV" }),
}) {}

export class UpdateOrganization extends Schema.Class<UpdateOrganization>("UpdateOrganization")({
  name: Schema.optional(Schema.String.pipe(Schema.minLength(1))),
  legalName: Schema.optional(Schema.String.pipe(Schema.minLength(1))),
  addressLine1: Schema.optional(Schema.NullOr(Schema.String)),
  addressLine2: Schema.optional(Schema.NullOr(Schema.String)),
  city: Schema.optional(Schema.NullOr(Schema.String)),
  state: Schema.optional(Schema.NullOr(Schema.String)),
  postalCode: Schema.optional(Schema.NullOr(Schema.String)),
  countryCode: Schema.optional(CountryCode),
  taxId: Schema.optional(Schema.NullOr(Schema.String)),
  taxIdType: Schema.optional(Schema.NullOr(TaxIdType)),
  email: Schema.optional(Schema.NullOr(Email)),
  phone: Schema.optional(Schema.NullOr(Schema.String)),
  website: Schema.optional(Schema.NullOr(Schema.String)),
  bankName: Schema.optional(Schema.NullOr(Schema.String)),
  bankIban: Schema.optional(Schema.NullOr(Schema.String)),
  bankSwift: Schema.optional(Schema.NullOr(Schema.String)),
  bankAccountNumber: Schema.optional(Schema.NullOr(Schema.String)),
  logoUrl: Schema.optional(Schema.NullOr(Schema.String)),
  defaultCurrency: Schema.optional(CurrencyCode),
  defaultPaymentTermsDays: Schema.optional(PositiveInt),
  invoicePrefix: Schema.optional(Schema.String),
}) {}
